services:
    redis:
        image: redis:7.2
        container_name: my-redis
        ports:
          - "6379:6379"
        volume:
          - redis-data:/data
        environment:
          - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}--appendonly yes
        restart: unless-stopped
        healthcheck:
          test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
          intervals: 10s
          timeout: 5s
          retries: 5
volume:
    redis-data:
        driver: local


